### ISSUE TITLE
Error using docker 

### ISSUE THREAD

**Issue by Er-WaN** [Tentacule/PgsToSrt#18]
Hi, 

I want to convert .sup (PGS) to .srt with your libs using docker : 

`docker run -it -v /share/CACHEDEV1_DATA/Multimedia/Movies/Test:/data -e INPUT=/data/Mission.Impossible.Fallout.2018.MULTi.TRUEFRENCH.2160p.UHD.BluRay.REMUX.DV.HEVC-BEO.6.en.sup -e LANGUAGE=eng tentacule/pgstosrt `

But I have this error : 

2020/12/11 11:36:28.418|ERROR|Error: Exception has been thrown by the target of an invocation.   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Tncl.NativeLoader.NativeInstance.CreateInstance(NativeLoader loader, Type interfaceType)
   at PgsToSrt.TesseractApi.Initialize()
   at PgsOcr.DoOcr() Exception has been thrown by the target of an invocation.

I have a QNAP NAS.

Thanks in advance for your help.

Erwan

**Comment by Tentacule** [comment]
I changed the parent image, it should be ok now.

**Comment by nation-wide** [comment]
I'm getting this same error. Using 1.2.0.0 without Docker.

dotnet PgsToSrt.dll --input "The Sopranos - S01E01 - The Sopranos.mkv" --output ./subtitles.srt --track 4

```
<snipped bunch of "Detected tesseract..." lines>
2020/12/18 14:04:43.929|INFO|Detected tesseract language data for language 'ara'.
2020/12/18 14:06:18.886|INFO|Starting OCR for 836 items...
2020/12/18 14:06:18.999|ERROR|Error: Exception has been thrown by the target of an invocation.   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Tncl.NativeLoader.NativeInstance.CreateInstance(NativeLoader loader, Type interfaceType)
   at PgsToSrt.TesseractApi.Initialize()
   at PgsOcr.DoOcr() Exception has been thrown by the target of an invocation.
```

**Comment by Tentacule** [comment]
You can try with v1.3.0, if it still doesn't work please add the linux distrubion name/version used.
